import { Menu } from './menu.model';

export const verticalMenuItems = [ 
    new Menu (1, 'Dashboard', '/', null, 'dashboard', null, false, 0),
    new Menu (3, 'CRM', null, null, 'computer', null, true, 0), 
    new Menu (4, 'Relaties', '/users', null, 'keyboard', null, false, 3), 
    new Menu (5, 'Contactpersonen', '/users', null, 'keyboard', null, false, 3),  
    new Menu (6, 'Concurenten', '/users', null, 'keyboard', null, false, 3), 
    new Menu (7, 'Leveradressen', '/users', null, 'keyboard', null, false, 3), 
    new Menu (8, 'ARTIKELEN', null, null, 'computer', null, true, 0), 
    new Menu (9, 'Artikelen', '/users', null, 'keyboard', null, false, 8), 
    new Menu (10, 'Diversen', '/users', null, 'keyboard', null, false, 8),
    new Menu (11, 'Artikelgroepen', '/users', null, 'keyboard', null, false, 8),
    new Menu (12, 'Serienummers', '/users', null, 'keyboard', null, false, 8),
    new Menu (13, 'Artikelen per leverancier', '/users', null, 'keyboard', null, false, 8),
    new Menu (14, 'Artikelen per debiteur', '/users', null, 'keyboard', null, false, 8),
    new Menu (15, 'STUKLIJSTEN', null, null, 'computer', null, true, 0), 
    new Menu (16, 'Stuklijsten', '/users', null, 'keyboard', null, false, 15), 
    new Menu (17, 'Stuklijstcalculatie', '/users', null, 'keyboard', null, false, 15), 
    new Menu (18, 'Serienummers', '/users', null, 'keyboard', null, false, 15), 
    new Menu (19, 'VERKOOP', null, null, 'computer', null, true, 0),
    new Menu (20, 'Verkoopoffertes', '/users', null, 'keyboard', null, false, 19),
    new Menu (21, 'Verkooporder', '/users', null, 'keyboard', null, false, 19),
    new Menu (22, 'Pakbon', '/users', null, 'keyboard', null, false, 19),
    new Menu (23, 'Combipakbon', '/users', null, 'keyboard', null, false, 19),
    new Menu (24, 'Verkoopfacturen', '/users', null, 'keyboard', null, false, 19),
    new Menu (25, 'INKOOP', null, null, 'computer', null, true, 0),
    new Menu (26, 'Inkoopoffertes', '/users', null, 'keyboard', null, false, 25),
    new Menu (27, 'Inkooporders', '/users', null, 'keyboard', null, false, 25),
    new Menu (28, 'Goederenontvangsten', '/users', null, 'keyboard', null, false, 25),
    new Menu (29, 'Inkoopfacturen', '/users', null, 'keyboard', null, false, 25),
    new Menu (30, 'FINANCIEEL', null, null, 'computer', null, true, 0),
    new Menu (31, 'Journaalposten', '/users', null, 'keyboard', null, false, 30),
    new Menu (31, 'Verdichte journaalposten', '/users', null, 'keyboard', null, false, 30),
    new Menu (32, 'Overzichten', '/users', null, 'keyboard', null, false, 30),
    new Menu (33, 'MEDEWERKERS', null, null, 'computer', null, true, 0),
    new Menu (34, 'Overzicht', '/users', null, 'supervisor_account', null, false, 33), 
    new Menu (35, 'Toegang regels', '/users', null, 'supervisor_account', null, false, 33),
    new Menu (200, 'Instellingen', null, null, 'more_horiz', null, true, 3),
    new Menu (201, 'Adressen', '/crm/instellingen/adressen', null, 'supervisor_account', null, false, 200),
    new Menu (202, 'Provincies', '/crm/instellingen/provincies', null, 'supervisor_account', null, false, 200),
    new Menu (203, 'Landen', '/crm/instellingen/landen', null, 'supervisor_account', null, false, 200),
    new Menu (204, 'Talen', '/crm/instellingen/talen', null, 'supervisor_account', null, false, 200),
    new Menu (205, 'Relatietypes', '/crm/instellingen/relatietypes', null, 'supervisor_account', null, false, 200),
    new Menu (206, 'Bedrijfstakken', '/crm/instellingen/bedrijfstakken', null, 'supervisor_account', null, false, 200),
    new Menu (207, 'Relatiegroepen', '/crm/instellingen/relatiegroepen', null, 'supervisor_account', null, false, 200),
    new Menu (209, 'Relatiebronnen', '/crm/instellingen/relatiebronnen', null, 'supervisor_account', null, false, 200),
    new Menu (210, 'Financiele status', '/crm/instellingen/financiele-status', null, 'supervisor_account', null, false, 200),
    new Menu (211, 'Rechtsvormen', '/crm/instellingen/rechtsvormen', null, 'supervisor_account', null, false, 200),
    new Menu (212, 'Titels', '/crm/instellingen/titels', null, 'supervisor_account', null, false, 200),
    new Menu (214, 'Functies', '/crm/instellingen/functies', null, 'supervisor_account', null, false, 200),
    new Menu (215, 'Personen', '/crm/instellingen/personen', null, 'supervisor_account', null, false, 200),
    new Menu (300, 'Instellingen', null, null, 'more_horiz', null, true, 8),
    new Menu (301, 'Artikeleenheden', '/users', null, 'supervisor_account', null, false, 300),
    new Menu (302, 'Merken', '/users', null, 'supervisor_account', null, false, 300),
    new Menu (400, 'Instellingen', null, null, 'more_horiz', null, true, 15),
    new Menu (401, 'Calculatieparameters', '/users', null, 'supervisor_account', null, false, 400),
    new Menu (500, 'Instellingen', null, null, 'more_horiz', null, true, 19),
    new Menu (501, 'Ordercategorieen', '/users', null, 'supervisor_account', null, false, 500),
    new Menu (502, 'Termijncodes', '/users', null, 'supervisor_account', null, false, 500),
    new Menu (503, 'Regelgroepen', '/users', null, 'supervisor_account', null, false, 500),
    new Menu (504, 'Bestelwijzen', '/users', null, 'supervisor_account', null, false, 500),
    new Menu (505, 'Redenen voor afwijzing', '/users', null, 'supervisor_account', null, false, 500),
    new Menu (506, 'Expediteuren', '/users', null, 'supervisor_account', null, false, 500),
    new Menu (507, 'Incoterms', '/users', null, 'supervisor_account', null, false, 500),
    new Menu (600, 'Instellingen', null, null, 'more_horiz', null, true, 25),
    new Menu (601, 'Regelgroepen', '/users', null, 'supervisor_account', null, false, 600),
    new Menu (602, 'Bestelwijzen', '/users', null, 'supervisor_account', null, false, 600),
    new Menu (603, 'Incoterms', '/users', null, 'supervisor_account', null, false, 600),
    new Menu (604, 'Redenen voor afwijzing', '/users', null, 'supervisor_account', null, false, 600),
    new Menu (605, 'Kwaliteitscodes', '/users', null, 'supervisor_account', null, false, 600),
    new Menu (606, 'Termijncodes', '/users', null, 'supervisor_account', null, false, 600),
    new Menu (700, 'Instellingen', null, null, 'more_horiz', null, true, 30),
    new Menu (701, 'Dagboeken', '/users', null, 'supervisor_account', null, false, 700),
    new Menu (702, 'Grootboekrekeningen', '/users', null, 'supervisor_account', null, false, 700),
    new Menu (703, 'BTW-codes', '/users', null, 'supervisor_account', null, false, 700),
    new Menu (704, 'Boekingstypes', '/users', null, 'supervisor_account', null, false, 700),
    new Menu (705, 'BTW-bedrijfsgroepen', '/users', null, 'supervisor_account', null, false, 700),
    new Menu (706, 'Boekjaren', '/users', null, 'supervisor_account', null, false, 700),
    new Menu (707, 'Betalingscondities', '/users', null, 'supervisor_account', null, false, 700),
    new Menu (708, 'Valutas', '/users', null, 'supervisor_account', null, false, 700),
    new Menu (709, 'Kostenplaatsen', '/users', null, 'supervisor_account', null, false, 700),
    new Menu (710, 'Kostendragers', '/users', null, 'supervisor_account', null, false, 700),
    new Menu (711, 'Betalingswijzen', '/users', null, 'supervisor_account', null, false, 700),
]

export const horizontalMenuItems = [ 
    new Menu (1, 'Dashboard', '/', null, 'dashboard', null, false, 0),
    new Menu (2, 'Users', '/users', null, 'supervisor_account', null, false, 0), 
    new Menu (3, 'UI Features', null, null, 'computer', null, true, 0),   
    new Menu (4, 'Buttons', '/ui/buttons', null, 'keyboard', null, false, 3),  
    new Menu (5, 'Cards', '/ui/cards', null, 'card_membership', null, false, 3), 
    new Menu (6, 'Lists', '/ui/lists', null, 'list', null, false, 3), 
    new Menu (7, 'Grids', '/ui/grids', null, 'grid_on', null, false, 3), 
    new Menu (8, 'Tabs', '/ui/tabs', null, 'tab', null, false, 3), 
    new Menu (9, 'Expansion Panel', '/ui/expansion-panel', null, 'dns', null, false, 3), 
    new Menu (10, 'Chips', '/ui/chips', null, 'label', null, false, 3),
    new Menu (11, 'Progress', '/ui/progress', null, 'data_usage', null, false, 3), 
    new Menu (12, 'Dialog', '/ui/dialog', null, 'open_in_new', null, false, 3), 
    new Menu (13, 'Tooltip', '/ui/tooltip', null, 'chat_bubble', null, false, 3), 
    new Menu (14, 'Snackbar', '/ui/snack-bar', null, 'sms', null, false, 3),
    new Menu (16, 'Mailbox', '/mailbox', null, 'email', null, false, 40), 
    new Menu (17, 'Chat', '/chat', null, 'chat', null, false, 40), 
    new Menu (20, 'Form Controls', null, null, 'dvr', null, true, 0), 
    new Menu (21, 'Autocomplete', '/form-controls/autocomplete', null, 'short_text', null, false, 20), 
    new Menu (22, 'Checkbox', '/form-controls/checkbox', null, 'check_box', null, false, 20), 
    new Menu (23, 'Datepicker', '/form-controls/datepicker', null, 'today', null, false, 20), 
    new Menu (24, 'Form field', '/form-controls/form-field', null, 'view_stream', null, false, 20), 
    new Menu (25, 'Input', '/form-controls/input', null, 'input', null, false, 20), 
    new Menu (26, 'Radio button', '/form-controls/radio-button', null, 'radio_button_checked', null, false, 20), 
    new Menu (27, 'Select', '/form-controls/select', null, 'playlist_add_check', null, false, 20), 
    new Menu (28, 'Slider', '/form-controls/slider', null, 'tune', null, false, 20), 
    new Menu (29, 'Slide toggle', '/form-controls/slide-toggle', null, 'star_half', null, false, 20),    
    new Menu (30, 'Tables', null, null, 'view_module', null, true, 0),
    new Menu (31, 'Basic', '/tables/basic', null, 'view_column', null, false, 30), 
    new Menu (32, 'Paging', '/tables/paging', null, 'last_page', null, false, 30), 
    new Menu (33, 'Sorting', '/tables/sorting', null, 'sort', null, false, 30),
    new Menu (34, 'Filtering', '/tables/filtering', null, 'format_line_spacing', null, false, 30),
    new Menu (35, 'Selecting', '/tables/selecting', null, 'playlist_add_check', null, false, 30),
    new Menu (36, 'NGX DataTable', '/tables/ngx-table', null, 'view_array', null, false, 30),  
    new Menu (70, 'Charts', null, null, 'multiline_chart', null, true, 0),
    new Menu (71, 'Bar Charts', '/charts/bar', null, 'insert_chart', null, false, 70),
    new Menu (72, 'Pie Charts', '/charts/pie', null, 'pie_chart', null, false, 70),
    new Menu (73, 'Line Charts', '/charts/line', null, 'show_chart', null, false, 70),
    new Menu (74, 'Bubble Charts', '/charts/bubble', null, 'bubble_chart', null, false, 70),    
    new Menu (81, 'Drag & Drop', '/drag-drop', null, 'mouse', null, false, 3), 
    new Menu (85, 'Material Icons', '/icons', null, 'insert_emoticon', null, false, 3),
    new Menu (40, 'Pages', null, null, 'library_books', null, true, 0),
    new Menu (43, 'Login', '/login', null, 'exit_to_app', null, false, 40),    
    new Menu (44, 'Register', '/register', null, 'person_add', null, false, 40),
    new Menu (45, 'Blank', '/blank', null, 'check_box_outline_blank', null, false, 40),
    new Menu (46, 'Page Not Found', '/pagenotfound', null, 'error_outline', null, false, 40),
    new Menu (47, 'Error', '/error', null, 'warning', null, false, 40),
    new Menu (48, 'Search', '/search', null, 'search', null, false, 40),
    new Menu (49, 'Landing', '/landing', null, 'filter', null, false, 40),
    new Menu (50, 'Schedule', '/schedule', null, 'event_note', null, false, 40),
    new Menu (200, 'External Link', null, 'http://themeseason.com', 'open_in_new', '_blank', false, 40),
    new Menu (66, 'Maps', null, null, 'map', null, true, 0),
    new Menu (67, 'Google', '/maps/googlemaps', null, 'location_on', null, false, 66),
    new Menu (68, 'Leaflet', '/maps/leafletmaps', null, 'my_location', null, false, 66),
]